### ISSUE TITLE
Empty gadget on 7.7 JIRA

### ISSUE THREAD

**Issue by gegabit** [mesilat/week-load-gadget#1]
Gadget is blank (empty) on new version JIRA 7.7. 
On 7.6 it was work fine.

**Comment by mesilat** [comment]
Hi, would you please flush your browser cache and retry? It could be something relating to your JIRA upgrade as I have tested the plugin with JIRA 7.7 and it worked fine. You may also test with different browser. Let me know if it helps

**Comment by gegabit** [comment]
Hello!

I try on Chrome, Yandex browser and Explorer. Its empty.

Screenshot (admin give me plugin screenshot on admin panel) + my JIRA desktop panel with plugin.

Catalina log don’t have any errors on week-load-gadget…

**Comment by mesilat** [comment]
What is your JIRA instance backend database? This could be a database-related issue.
Also you may check your browser console for any errors. Please copy them here

**Comment by gegabit** [comment]
Hello!
Database is MySQL.
In log we have some error (look at pic).
Log in attach.

2018-01-17 19:15 GMT+03:00 Mesilat Limited <notifications@github.com>:

**Comment by mesilat** [comment]
Can't find log or pic, could you please just copy it in plain text?

**Comment by gegabit** [comment]
![error_jira](https://user-images.githubusercontent.com/6592191/35151013-b1d0d7aa-fd2d-11e7-97b7-6f03654b77b3.png)
[jira.ru-1516205910038.log](https://github.com/mesilat/week-load-gadget/files/1646484/jira.ru-1516205910038.log)
ops, on mail reply dont attach =(

**Comment by mesilat** [comment]
Will you please try version 1.0.1 -- https://github.com/mesilat/week-load-gadget/releases/tag/v1.0.1
I removed dependency on **define** and **require** libraries. Please install pre-release https://github.com/mesilat/week-load-gadget/releases/download/v1.0.1/week-load-gadget-1.0.1.jar

**Comment by gegabit** [comment]
Now its works fine. Thank you.

**Comment by babinvn** [comment]
Thanks for your feedback. I deployed the updated version to Atlassian Marketplace
