### ISSUE TITLE
The time record  is displayed at previous week if created on Monday

### ISSUE THREAD

**Issue by alex-fed91** [mesilat/week-load-gadget#2]
JIRA v7.7.0
Weekly Activity Gadget  -- 1.0.1

if you record the time in the task at Monday morning,the record is displayed on the gadget 7 days earlier.

Moreover, inside the task itself, the time record is displayed correctly. (in the Journal of Works)

Screenshots for clarity:
![Screenshot_1](https://user-images.githubusercontent.com/57092376/67670356-2819df80-f98d-11e9-91ec-b56f37a1bad0.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/57092376/67670361-2a7c3980-f98d-11e9-903f-b575da6c5a01.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/57092376/67670363-2cde9380-f98d-11e9-97b9-65d69d010532.jpg)

**This behavior is seen precisely when creating recordings on Monday morning**

**Comment by mesilat** [comment]
Hi,
What timezone is your client and your server? Doest this problem persist or happen from time to time?

**Comment by alex-fed91** [comment]
Hello,
Server and client are in the UTC + 3 time zone,and another client in UTC + 4 time zone. 
This problem is constant. Was seen a couple of months ago.

**Comment by mesilat** [comment]
I have just tested with Russian locale and Moscow timezone and everything seems to work fine:

![Screenshot 2019-10-29 at 13 52 42](https://user-images.githubusercontent.com/18350871/67761106-ae005e00-fa53-11e9-9b34-48294216be66.png)

![Screenshot 2019-10-29 at 13 52 24](https://user-images.githubusercontent.com/18350871/67761134-b8baf300-fa53-11e9-9152-228c708874e9.png)

Am I missing something? Could you please help me reproduce the issue.
By the way, do you use the latest version of the plugin?

**Comment by alex-fed91** [comment]
No you didn't

Sorry, I made a mistake
version 1.0.1 , maybe this is the reason?
![image](https://user-images.githubusercontent.com/57092376/67770408-c54d4480-fa6f-11e9-8d11-88028259829f.png)


in marketplace I found 1.0.8 version 
![image](https://user-images.githubusercontent.com/57092376/67770943-ca5ec380-fa70-11e9-9b9f-654f327009c2.png)

**Comment by mesilat** [comment]
Yes, please upgrade to latest version and let me know if the issue persists

**Comment by mesilat** [comment]
I guess this issue can be closed, as no feedback from the reporter
